import { Footer } from "@/components/Footer";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import CompanyBrand from "../../public/images/remove-brand.svg";
import Image from "next/image";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="bg-[#212126] text-white h-[113px]">
          <div className="container mx-auto">
            <Image className="pt-10" src={CompanyBrand} alt="teste" />
          </div>
        </header>
        <main>{children}</main>
        <Footer>Copy </Footer>
      </body>
    </html>
  );
}
